### PR TITLE
add libmaple STM32F1 SoftwareSerial capable define

### PR DESCRIPTION
**Pull request by GerogeFu**
If you add this , so i can add software serial for stm32f1 boards.

### CODE REVIEW

**Comment by teemuatlut** [comment]
Thanks!

**Comment by thinkyhead** [comment]
For some reason some of our STM32F1x platforms can find `<SoftwareSerial.h>` while others cannot. See recent comments on MarlinFirmware/Marlin#14832

**Comment by tpruvot** [comment]
Which pio/arduino lib are you using for the STM32 ?

**Comment by teemuatlut** [comment]
@thinkyhead Do you know how many of our build tools support `__has_include`?

**Comment by thinkyhead** [comment]
I have been told that we can use `#ifdef __has_include` to check for its existence, because it is a builtin of the preprocessor.

**Comment by thinkyhead** [comment]
Unfortunately, you can't test for platform headers with `__has_include(<Arduino.h>)`. It always returns false.

**Comment by thinkyhead** [comment]
Aha, actually this did work. Not sure if it works with `defined(__has_include)` on the same line as the test.
```cpp
#ifdef __has_include
  #if __has_include(<Arduino.h>)
    #error "Arduino.h is seen by __has_include!"
  #else
    #error "Arduino.h is NOT seen by __has_include!"
  #error
#endif
```

**Comment by thinkyhead** [comment]
Nope. Don't do this:
```cpp
#if defined(__has_include) && __has_include(<Arduino.h>)
```

**Comment by tpruvot** [comment]
its not that some find it.. its just all the F1 which doesnt find it.. Others does not include it at all. This release change is only for STM32F1

**Comment by teemuatlut** [comment]
b9b3796584f31dd1d499c73a097be4e9ee91cf24

**Comment by thinkyhead** [comment]
That patch will be helpful to future-proof the library. So basically, any platform that's using C++17 will be able to avoid the include automagically. But note that if the library isn't installed, there will be no `#include` error. But other undefined symbol errors will still pop up.

**Comment by teemuatlut** [comment]
Yea if the library isn't installed (maybe because the platform doesn't have it), then you can't use SW Serial. Makes sense to me but I need to think about whether or not I want to add a more verbal warning of some sort.
I think C++ had a `deleted` or `deprecated` features I could use if a user was trying to invoke a constructor the compiler doesn't have access to.

**Comment by thinkyhead** [comment]
> I think C++ had a deleted or deprecated features I could use…

I've seen some tricks employed to add warnings to deprecated things and errors to obsolete things, but I've never seen official support in C++ yet. But I grabbed the new specification PDF so I'll see if it mentions it.

**Comment by thinkyhead** [comment]
Ah, yes. Here it is…
```cpp
[[ deprecated ]] void hello() { printf("Hello"); }
```

**Comment by thinkyhead** [comment]
And we also have… `[[ maybe_unused ]]` which will allow us to get rid of `UNUSED(thing)` eventually.

**Comment by teemuatlut** [comment]
Also see https://en.cppreference.com/w/cpp/language/function#Deleted_functions
> Any use of a deleted function is ill-formed (the program will not compile).

**Comment by GerogeFu** [comment]
I think we can change ARDUINO_ARCH_STM32F1 to ARDUINO_ARCH_STM32 to support all stm32 not only stm32f1

**Pull request merged**
