### PR TITLE
add SoftwareSerial for stm32f1/stm32f4

### PR DESCRIPTION
**Pull request by Msq001**
#51 
I have tested it in stm32f103 and stm32f407,  So far, it works normal.

### CODE REVIEW

**Comment by gloomyandy** [comment]
Does it really make sense to have software serial for some devices in the TMC library but in the framework for others? I'm not saying this is wrong, but it seems strange to have this split. Is there a reason why you have decided to add the software serial routines here rather than including them in the mcu framework (or even in the Marlin HAL)? I would also worry a little about choice of a resource like a timer being made here, it seems that it would be easy for something in the Marlin HAL or framework to decide to use the same timer without realising that this library may already be using it.

**Comment by Msq001** [comment]
Because of additional hardware resources(TIMER ) are needed, so it is not actually a general library. I don't think it's appropriate to put it in the MCU framework. Maybe it's better to put it in Marlin Hal, and put software serial timer number with the temperature and the stepper timer number.

**Comment by gloomyandy** [comment]
Having thought about this some more....
1. Marlin and I think this library uses the Arduino as its "model"  for how things work and on the Arduino the software serial implementation is within the framework.
2. Adding this code to the TMC library in effect means that whoever looks after this TMC library will also need to maintain the software serial implementation (and will almost certainly face requests to extend it to other platforms). I'm not sure that this is the best place to have that code maintained (I know I would not want to have it).

My understanding is that unlike the LPC176x the various STM processors do not share an Arduino like framework targeted primarily at Marlin. As a result it may not be possible to easily get the software serial code included in the framework. So perhaps the best place for this code would be as part of the Marlin HAL (or maybe as a library within Marlin). That way folks that have the appropriate hardware can test and maintain it.

I would also like to draw attention to the fact that this code makes use of digitalRead and digitalWrite to perform I/O requests. My understanding is that in some situations these functions can be considerably slower than the gpio_* routines used by my original LPC176x code. Now the timing of the interrupt routine used by this code is very critical (and I spent a lot of time on this in the original implementation), because it can introduce jitter into the Marlin stepper output. I'm not really familiar enough with the various STM processors but it is something that you should be aware of before running this code when the stepper motors are active. I would strongly recommend that someone tests how long the interrupt routine in this code takes to execute (for both read and write operations). Looking at my notes from the 176x implementation the total time for the ISR was around 1uS. I think that ideally this should be considered the target time.

Oh and really the header comment in this code should be updated as it mainly refers to the various Arduino implementations. This was really something I should have done, but the code got merged before I got around to making the changes!

**Comment by Msq001** [comment]
Yeah. put it in Marlin HAL is better,  I will do this,  and do more test about you have recommend, and give some feedback here

**Comment by gloomyandy** [comment]
@Msq001 I have another thing about Marlin and the SKR V1.3 board I'd like to discus with you and have tried to send you an email (not sure if it got to you). Is there a good way to get in touch with you? Thanks.

**Comment by Msq001** [comment]
my email: 3001154986@qq.com

**Comment by teemuatlut** [comment]
Libraries cannot use implementations from Marlin.
I don't want to add functionality into a general library when it would much better belong into the MCU framework. It unnecessarily complicates things and I definitely don't want to maintain it.

This doesn't compile on all necessary platforms.

**Comment by Msq001** [comment]
Okay, maybe I need to create PR into the MCU-framework. As gloomyandy said above, STM32 does not have a framework  targeted primarily at Marlin like lpc176x. So more work may be needed if want to merge this software serial to framework, and I will do that

**Comment by teemuatlut** [comment]
You can separate your library implementation into its own library and register that with PIO.
Then that library can be added as a dependency and STM can be added as a SW Serial supported platform.

**Pull request closed without merging**
