### PR TITLE
Fix support for BIGTECHTREE SKR 1.3 board

### PR DESCRIPTION
**Pull request by extesy**
I had a problem with the board not working (it's based on LPC1768) and their tech support suggested this change which fixed the problem. Instead of keeping the fix locally I think it's better to merge it upstream.

### CODE REVIEW

**Comment by teemuatlut** [comment]
This very significantly reduces the SPI clock speed, by more than 90% and I won't consider it as a proper fix. I can look into it when I can but if the SPI connectivity on a somewhat popular board like the SKR1.3 was this fundamentally broken, I think we would've seen more reports coming in as the latest change has been in place for almost three months.

**Comment by extesy** [comment]
Thank you, @teemuatlut! This "fix" came directly from BIGTREETECH technical support so I am going to follow up with them again about this.

**Comment by Msq001** [comment]
this issue only found in tmc5160/5161 now,  tmc2130 can work normally. The communication of tmc5160 is abnormal at high speed.

**Comment by extesy** [comment]
@Msq001 So is this a hardware bug? Let's switch discussion to https://github.com/bigtreetech/BIGTREETECH-TMC5160-V1.0/issues/2 then.

**Comment by Neckbreak** [comment]
Might be a dumb question but i can't
 find "src/source/TMC_platforms.h" in Atom. Using Marlin 2 Bugfix fpr SKR

Unbenannt

**Comment by extesy** [comment]
@Neckbreak look under `.pio/libs`

**Pull request closed without merging**
