### PR TITLE
Attempt to fix ENDSTOP_INTERRUPTS_FEATURE (marlin fw) with TMC2130

### PR DESCRIPTION
**Pull request by Moyster**
Hi,  
I'm not sure if that's the proper way to deal with the vector conflicts (multiple definitions of __vector_9/10/11 when enabling TMCStepper lib and ENDSTOP_INTERRUPTS_FEATURE) but this got rid of the compile errors.  
As it seems passing flags from marlin sketch to the TMCStepper lib isn't possible, a kind of hack-ish way to workaround that would be to have the problematic flag in a separate header, allowing to include a TMCStepper_noSWCap.h without SW_CAPABLE_PLATFORM (or directly include TMCStepper_main.h for that matter).  

This way marlin could have a couple ifdefs in `src/module/stepper_indirection.h` and `src/feature/tmc_util.h` to enable ENDSTOP_INTERRUPTS_FEATURE on tmc2130.  

Hope that helps :)

### CODE REVIEW

**Comment by teemuatlut** [comment]
After a very quick look, my thought is that when the compiler is going through lets say `TMCStepper.cpp`, that compile unit then includes `TMCStepper_main.h` header. In that header there is no `SW_CAPABLE_PLATFORM` defined and `SoftwareSerial.h` for example is never included. Nor is any of the definitions compiled in.

I'd like to reiterate that this is after 5 minutes of looking at this, but it looks like SoftwareSerial side of the library is disabled and so your compile sure enough should succeed.

**Comment by Moyster** [comment]
Yeah, basically including TMCStepper.h should do the same as before this commit, but including TMCStepper_noSWCap.h allows to get rid of SoftwareSerial related code, so TMC2130 and the endstop interrupts feature can compile/work.  
That allows to add a couple ifdef in place like : https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/module/stepper_indirection.h#L59  
and include TMCStepper_noSWCap.h if TMC2130 and ENDSTOP_INT_FEAT are enabled in Marlin.

**Comment by teemuatlut** [comment]
No, I mean that even when it's compiling `TMCStepper.cpp` the SoftwareSerial code is disabled. Basically you can't influence `TMCStepper.cpp` compile unit with anything from `Marlin`.

**Comment by Moyster** [comment]
TMCStepper.h has the #define for SW_CAPABLE_PLATFORM, if I include TMCStepper.h the flag is applied from the library to the library, and it compiles with the SoftwareSerial includes / ifdef codes.  
Maybe I'm missing something, but I'm not trying to use anything from Marlin, so if Marlin handles which header to include, one of the header can have the SW_CAPABLE_PLATFORM define and not the other.

**Comment by teemuatlut** [comment]
Lets say I have a project where I want to use SW Serial, so I include `TMCStepper.h`.
Sure my project file does include `TMCStepper.h` and `TMCStepper_main.h` and so `SW_CAPABLE_PLATFORM` is defined in *this* source file.

But what happens when the compiler tries to compile `TMCStepper.cpp` for me?
It includes just the `TMCStepper_main.h` and so `SW_CAPABLE_PLATFORM` does **not** get defined.
Therefore also `SoftwareSerial.h` does not get included, nor does any of the SW Serial definitions.

So maybe we would then have `TMCStepper.cpp` include the full `TMCStepper.h`? But then we'd be back where we started where `SoftwareSerial.h` always gets included and thus you get the linker error.

**Comment by Moyster** [comment]
Right, thanks for the explanation, so the only solution is a "fork" without SW_CAPABLE_PLATFORM ?

**Comment by teemuatlut** [comment]
Unfortunately it seems to be a limitation of the SoftwareSerial library and you'll have to look into ways that the library is used with other pin interrupts. I don't think this is an outlandish idea and I would think it has been done in other projects. I just haven't look into it at all.

**Pull request closed without merging**
