### PR TITLE
Fixed recent issue introduced in making serial port stable and setting correct baud rate

### PR DESCRIPTION
**Pull request by jasonmnemonic**
* Changed serial port initialisation's VTIME=10 so that if anything goes wrong during serial read from driver, the PiOS will not seem to hang or block for 10s or sometimes 10s to 30s depending on retries. A timeout of 1s is enough. At least comment is there should anyone need to tweak it.
 * Added a more robust way to clear serial buffer if we are using a hardware serial. This is to sort out intermittent blocking or read issues. Do the same for writes as well to avoid general weirdness in serial port.bugs in bcm2835_stream.cpp's begin() to use different baud speed and to resolve general port or driver instability

This is to also resolve some stability issues as mentioned in https://github.com/teemuatlut/TMCStepper/issues/215

### CODE REVIEW

**Comment by teemuatlut** [comment]
This will break compiling for every other platform because they don't have `Stream::FlushOptions` and they do not accept arguments for `.flush`.

**Comment by jasonmnemonic** [comment]
Sorry. Is the enum FlushOptions definition not suitable in the Stream header? Do you prefer me to change to uint8_t instead of enum?

**Comment by teemuatlut** [comment]
The library needs to compile and work for AVR, LPC, STM32, ESP32, SAM, SAMD, ESP8266, Teensy, and RasPi. The number of users and therefore the priority would likely also be in this order.
The Release v1 branch has a better abstraction architecture between all these but I'm being very conservative with the release due to how extensive the update will be.

**Comment by jasonmnemonic** [comment]
I follow you but if you see my changeset, it looks like my code will work unless you are talking about some compilers might not like the syntax. If not, I can just use simple variables and parameters to make it compile-able to all.

The changes that I did has code that works like before changes and also if there is hardware to support it like the Pi then it is improvements. I see the code is no worse than before but do let me know what you think?

I can change using uint8_t rather than enum so that syntax works for all. Whichever way you want to change, I will change for us. :-)

PS: actually let me think about the whole thing through. I will submit a different change for VTIME because that really needs changing.

**Pull request closed without merging**
