### PR TITLE
Don't clobber GCONF_register if we can't read from the driver

### PR DESCRIPTION
**Pull request by ManuelMcLure**
This fixes https://github.com/MarlinFirmware/Marlin/issues/15055.

### CODE REVIEW

**Comment by teemuatlut** [comment]
I'll merge this in later this evening. Probably time for a new release tag as well.

**Comment by ManuelMcLure** [comment]
I missed that we also have to do this for ``CHOPCONF()`` - I'll update the PR later today when I get off work. We can probably skip ``FACTORY_CONF()`` since it's not called anywhere in Marlin.

**Comment by ManuelMcLure** [comment]
Also applied the same fix to ``PWMCONF()`` and ``FACTORY_CONF()``.

**Comment by ManuelMcLure** [comment]
And I still missed doing it for ``CHOPCONF()`` - need to add another commit.

**Comment by delwinbest** [comment]
Any idea when this might be merged? I'm testing the changes locally - so far, so good. Thank you!
Stealchop at lower speeds (80mm/s) works well, spreadcycle, the same (80mm/s > 120mm/s). 
Hybrid mode, using these thresholds on Marlin, works in that it delivers smooth prints, but it is noisey (jerk noise) when the mode is changed. I suspect this to be normal operation though as I get the same jerk noise when issuing the M122 command with debug on.

**Comment by teemuatlut** [comment]
Hopefully during this week. I haven't had the time to do any printer related work for a long time.
Although right now I'm more leaning towards making the reads not override the cached values in any situation, as this would then favor intended register values over read back values.

**Comment by teemuatlut** [comment]
[v0.5.0](https://github.com/teemuatlut/TMCStepper/releases/tag/v0.5.0)

https://github.com/teemuatlut/TMCStepper/commit/1120e71a199f8fcb80722d490eec51025455097c

**Comment by ManuelMcLure** [comment]
Fixed in a different way.

**Pull request closed without merging**
